import type {
  CollectionDetail,
  ProjectDetail,
  QaMessage,
} from "@/lib/research/types";

function stringifyOutput(value: unknown) {
  if (!value) {
    return "Not generated yet.";
  }

  return JSON.stringify(value, null, 2);
}

function pinnedQa(qa: QaMessage[]) {
  const pinned = qa.filter((message) => message.pinned);
  return pinned.length ? pinned : qa.slice(0, 5);
}

export function buildMarkdownReport(project: ProjectDetail) {
  const document = project.documents[0];
  const lines = [
    `# ${project.title}`,
    "",
    `Generated by ResearchOS on ${new Date().toISOString()}.`,
    "",
    "## Source",
    "",
    document
      ? `- ${document.fileName} (${document.chunkCount} chunks, approximately ${document.tokenCount} tokens)`
      : "- No source document available.",
    "",
    "## Summary",
    "",
    "```json",
    stringifyOutput(project.outputs.summary),
    "```",
    "",
    "## Insights",
    "",
    "```json",
    stringifyOutput(project.outputs.insights),
    "```",
    "",
    "## Keywords",
    "",
    "```json",
    stringifyOutput(project.outputs.keywords),
    "```",
    "",
    "## Pinned Q&A",
    "",
  ];

  for (const message of pinnedQa(project.qa)) {
    lines.push(`### ${message.question}`);
    lines.push("");
    lines.push(message.answer);
    lines.push("");

    if (message.citations.length) {
      lines.push("Citations:");
      for (const citation of message.citations) {
        lines.push(
          `- Chunk ${citation.chunkIndex}: ${citation.quote.replace(/\s+/g, " ").slice(0, 220)}`,
        );
      }
      lines.push("");
    }
  }

  lines.push("## Notes");
  lines.push("");

  for (const note of project.notes) {
    lines.push(`- **${note.title}:** ${note.body}`);
  }

  lines.push("");
  lines.push("## Highlights");
  lines.push("");

  for (const highlight of project.highlights) {
    lines.push(`- ${highlight.quote.replace(/\s+/g, " ").slice(0, 240)}`);
  }

  return lines.join("\n");
}

export function buildJsonReport(project: ProjectDetail) {
  return JSON.stringify(
    {
      project: {
        id: project.id,
        title: project.title,
        createdAt: project.createdAt,
      },
      documents: project.documents,
      outputs: project.outputs,
      pinnedQa: pinnedQa(project.qa),
      notes: project.notes,
      highlights: project.highlights,
      citations: project.qa.flatMap((message) => message.citations),
    },
    null,
    2,
  );
}

export function buildCollectionMarkdownReport(collection: CollectionDetail) {
  const lines = [
    `# ${collection.name}`,
    "",
    `Generated by ResearchOS on ${new Date().toISOString()}.`,
    "",
    "## Sources",
    "",
    ...collection.documents.map(
      (document) =>
        `- ${document.projectTitle}${document.fileName ? ` (${document.fileName})` : ""}`,
    ),
    "",
    "## Latest Synthesis",
    "",
  ];

  const latestReport = collection.reports[0];
  if (latestReport) {
    lines.push(`### ${latestReport.title}`);
    lines.push("");
    lines.push("```json");
    lines.push(stringifyOutput(latestReport.output));
    lines.push("```");
    lines.push("");
  } else {
    lines.push("No synthesis report generated yet.");
    lines.push("");
  }

  lines.push("## Collection Notes");
  lines.push("");
  for (const note of collection.notes) {
    lines.push(`- **${note.title}:** ${note.body}`);
  }

  lines.push("");
  lines.push("## Linked Insights");
  lines.push("");
  for (const insight of collection.insights) {
    lines.push(`- **${insight.title}:** ${insight.body}`);
  }

  lines.push("");
  lines.push("## Research Claims");
  lines.push("");
  for (const claim of collection.claims) {
    lines.push(`- **${claim.stance}:** ${claim.claim}`);
    lines.push(`  Evidence: ${claim.evidence}`);
  }

  lines.push("");
  lines.push("## Entities");
  lines.push("");
  for (const entity of collection.entities) {
    lines.push(`- **${entity.name}** (${entity.type}): ${entity.summary}`);
  }

  lines.push("");
  lines.push("## Concept Links");
  lines.push("");
  for (const relationship of collection.relationships) {
    lines.push(
      `- **${relationship.sourceName}** ${relationship.relation} **${relationship.targetName}** (${Math.round(relationship.strength * 100)}%): ${relationship.evidence ?? "No evidence note."}`,
    );
  }

  lines.push("");
  lines.push("## Research Sessions");
  lines.push("");
  for (const session of collection.sessions) {
    lines.push(`### ${session.title}`);
    lines.push("");
    lines.push(session.summary ?? "No session summary saved.");
    lines.push("");
    for (const finding of session.findings) {
      lines.push(`- **${finding.findingType}:** ${finding.title} - ${finding.body}`);
    }
    lines.push("");
  }

  lines.push("");
  lines.push("## Collection Q&A");
  lines.push("");
  for (const message of collection.qa.slice(0, 8)) {
    lines.push(`### ${message.question}`);
    lines.push("");
    lines.push(message.answer);
    lines.push("");
    if (message.citations.length) {
      lines.push("References:");
      for (const citation of message.citations) {
        lines.push(
          `- ${citation.projectTitle ?? "Source"} chunk ${citation.chunkIndex}: ${citation.quote.replace(/\s+/g, " ").slice(0, 220)}`,
        );
      }
      lines.push("");
    }
  }

  return lines.join("\n");
}

export function buildCollectionJsonReport(collection: CollectionDetail) {
  return JSON.stringify(
    {
      collection: {
        id: collection.id,
        name: collection.name,
        createdAt: collection.createdAt,
      },
      documents: collection.documents,
      notes: collection.notes,
      reports: collection.reports,
      entities: collection.entities,
      documentEntities: collection.documentEntities,
      relationships: collection.relationships,
      insights: collection.insights,
      claims: collection.claims,
      sessions: collection.sessions,
      qa: collection.qa,
      citations: [
        ...collection.reports.flatMap((report) => report.citations),
        ...collection.qa.flatMap((message) => message.citations),
      ],
    },
    null,
    2,
  );
}
