import type { ProjectDetail, QaMessage } from "@/lib/research/types";

function stringifyOutput(value: unknown) {
  if (!value) {
    return "Not generated yet.";
  }

  return JSON.stringify(value, null, 2);
}

function pinnedQa(qa: QaMessage[]) {
  const pinned = qa.filter((message) => message.pinned);
  return pinned.length ? pinned : qa.slice(0, 5);
}

export function buildMarkdownReport(project: ProjectDetail) {
  const document = project.documents[0];
  const lines = [
    `# ${project.title}`,
    "",
    `Generated by ResearchOS on ${new Date().toISOString()}.`,
    "",
    "## Source",
    "",
    document
      ? `- ${document.fileName} (${document.chunkCount} chunks, approximately ${document.tokenCount} tokens)`
      : "- No source document available.",
    "",
    "## Summary",
    "",
    "```json",
    stringifyOutput(project.outputs.summary),
    "```",
    "",
    "## Insights",
    "",
    "```json",
    stringifyOutput(project.outputs.insights),
    "```",
    "",
    "## Keywords",
    "",
    "```json",
    stringifyOutput(project.outputs.keywords),
    "```",
    "",
    "## Pinned Q&A",
    "",
  ];

  for (const message of pinnedQa(project.qa)) {
    lines.push(`### ${message.question}`);
    lines.push("");
    lines.push(message.answer);
    lines.push("");

    if (message.citations.length) {
      lines.push("Citations:");
      for (const citation of message.citations) {
        lines.push(
          `- Chunk ${citation.chunkIndex}: ${citation.quote.replace(/\s+/g, " ").slice(0, 220)}`,
        );
      }
      lines.push("");
    }
  }

  lines.push("## Notes");
  lines.push("");

  for (const note of project.notes) {
    lines.push(`- **${note.title}:** ${note.body}`);
  }

  lines.push("");
  lines.push("## Highlights");
  lines.push("");

  for (const highlight of project.highlights) {
    lines.push(`- ${highlight.quote.replace(/\s+/g, " ").slice(0, 240)}`);
  }

  return lines.join("\n");
}

export function buildJsonReport(project: ProjectDetail) {
  return JSON.stringify(
    {
      project: {
        id: project.id,
        title: project.title,
        createdAt: project.createdAt,
      },
      documents: project.documents,
      outputs: project.outputs,
      pinnedQa: pinnedQa(project.qa),
      notes: project.notes,
      highlights: project.highlights,
      citations: project.qa.flatMap((message) => message.citations),
    },
    null,
    2,
  );
}
